import { Task } from './src/types/task';

function addDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setUTCDate(result.getUTCDate() + days);
  return result;
}

function setTime(date: Date, hours: number, minutes = 0, seconds = 0): Date {
  const result = new Date(date);
  result.setUTCHours(hours, minutes, seconds, 0);
  return result;
}

function formatISO(date: Date): string {
  return date.toISOString().split('.')[0] + 'Z';
}

const today = new Date();
const baseDate = setTime(new Date(today), 0, 0, 0);

export const sourceTasks: Task[] = [
  {
    id: '1',
    name: 'Project Kickoff',
    startDate: formatISO(setTime(addDays(baseDate, 0), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 0), 11)),
    parentId: null,
    sequence: '1',
    dependencies: [],
  },
  {
    id: '2',
    name: 'Requirement Gathering',
    startDate: formatISO(setTime(addDays(baseDate, 1), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 4), 17)),
    parentId: null,
    sequence: '2',
    dependencies: [{ targetId: '1', type: 'FS' }],
  },
  {
    id: '3',
    name: 'Design Kickoff Meeting',
    startDate: formatISO(setTime(addDays(baseDate, 3), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 3), 17)),
    parentId: null,
    sequence: '2.1',
    dependencies: [{ targetId: '2', type: 'SS' }],
  },
  {
    id: '4',
    name: 'Technical Design Review',
    startDate: formatISO(setTime(addDays(baseDate, 5), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 7), 17)),
    parentId: null,
    sequence: '3',
    dependencies: [{ targetId: '3', type: 'FS' }],
  },
  {
    id: '5',
    name: 'Frontend Architecture Planning',
    startDate: formatISO(setTime(addDays(baseDate, 8), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 10), 17)),
    parentId: null,
    sequence: '4',
    dependencies: [{ targetId: '4', type: 'FS' }],
  },
  {
    id: '6',
    name: 'Backend Architecture Planning',
    startDate: formatISO(setTime(addDays(baseDate, 9), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 11), 17)),
    parentId: null,
    sequence: '5',
    dependencies: [{ targetId: '4', type: 'FS' }],
  },
  {
    id: '7',
    name: 'Frontend UI Design',
    startDate: formatISO(setTime(addDays(baseDate, 12), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 17), 17)),
    parentId: '5',
    sequence: '4.1',
    dependencies: [{ targetId: '5', type: 'FS' }],
  },
  {
    id: '8',
    name: 'Backend Database Schema Design',
    startDate: formatISO(setTime(addDays(baseDate, 14), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 17), 17)),
    parentId: '6',
    sequence: '5.1',
    dependencies: [{ targetId: '6', type: 'FS' }],
  },
  {
    id: '9',
    name: 'User Authentication Development',
    startDate: formatISO(setTime(addDays(baseDate, 18), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 22), 17)),
    parentId: '7',
    sequence: '6',
    dependencies: [{ targetId: '7', type: 'FS' }],
  },
  {
    id: '10',
    name: 'Payment Integration Development',
    startDate: formatISO(setTime(addDays(baseDate, 18), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 22), 17)),
    parentId: '8',
    sequence: '7',
    dependencies: [{ targetId: '8', type: 'FS' }],
  },
  {
    id: '11',
    name: 'API Endpoints Development',
    startDate: formatISO(setTime(addDays(baseDate, 23), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 27), 17)),
    parentId: '9',
    sequence: '6.1',
    dependencies: [{ targetId: '9', type: 'SS' }],
  },
  {
    id: '12',
    name: 'Frontend Component Development',
    startDate: formatISO(setTime(addDays(baseDate, 23), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 28), 17)),
    parentId: '7',
    sequence: '4.2',
    dependencies: [{ targetId: '7', type: 'SS' }],
  },
  {
    id: '13',
    name: 'Integration of Frontend and Backend',
    startDate: formatISO(setTime(addDays(baseDate, 28), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 31), 17)),
    parentId: null,
    sequence: '8',
    dependencies: [
      { targetId: '11', type: 'FS' },
      { targetId: '12', type: 'FS' },
    ],
  },
  {
    id: '14',
    name: 'Performance Optimization',
    startDate: formatISO(setTime(addDays(baseDate, 32), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 35), 17)),
    parentId: null,
    sequence: '9',
    dependencies: [{ targetId: '13', type: 'FS' }],
  },
  {
    id: '15',
    name: 'User Acceptance Testing (UAT)',
    startDate: formatISO(setTime(addDays(baseDate, 36), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 39), 17)),
    parentId: null,
    sequence: '10',
    dependencies: [{ targetId: '14', type: 'FS' }],
  },
  {
    id: '16',
    name: 'Bug Fixing and Refinement',
    startDate: formatISO(setTime(addDays(baseDate, 40), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 43), 17)),
    parentId: null,
    sequence: '11',
    dependencies: [{ targetId: '15', type: 'FS' }],
  },
  {
    id: '17',
    name: 'Pre-Release Demo',
    startDate: formatISO(setTime(addDays(baseDate, 44), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 46), 17)),
    parentId: null,
    sequence: '12',
    dependencies: [{ targetId: '16', type: 'FS' }],
  },
  {
    id: '18',
    name: 'Final Release and Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 47), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 50), 17)),
    parentId: null,
    sequence: '13',
    dependencies: [{ targetId: '17', type: 'FS' }],
  },
  {
    id: '19',
    name: 'Post-Release Monitoring',
    startDate: formatISO(setTime(addDays(baseDate, 51), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 53), 17)),
    parentId: null,
    sequence: '14',
    dependencies: [{ targetId: '18', type: 'FS' }],
  },
  {
    id: '20',
    name: 'Community Engagement and Feedback Collection',
    startDate: formatISO(setTime(addDays(baseDate, 54), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 57), 17)),
    parentId: null,
    sequence: '15',
    dependencies: [{ targetId: '19', type: 'FS' }],
  },
  {
    id: '21',
    name: 'Feature Iteration and Updates',
    startDate: formatISO(setTime(addDays(baseDate, 58), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 60), 17)),
    parentId: null,
    sequence: '16',
    dependencies: [{ targetId: '20', type: 'SS' }],
  },
  {
    id: '22',
    name: 'Maintenance and Bug Fixing',
    startDate: formatISO(setTime(addDays(baseDate, 61), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 63), 17)),
    parentId: null,
    sequence: '17',
    dependencies: [{ targetId: '21', type: 'FS' }],
  },
  {
    id: '23',
    name: 'Database Optimization',
    startDate: formatISO(setTime(addDays(baseDate, 64), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 67), 17)),
    parentId: null,
    sequence: '18',
    dependencies: [{ targetId: '22', type: 'FS' }],
  },
  {
    id: '24',
    name: 'Scaling Infrastructure',
    startDate: formatISO(setTime(addDays(baseDate, 68), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 71), 17)),
    parentId: null,
    sequence: '19',
    dependencies: [{ targetId: '23', type: 'FS' }],
  },
  {
    id: '25',
    name: 'Security Patch Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 72), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 74), 17)),
    parentId: null,
    sequence: '20',
    dependencies: [{ targetId: '24', type: 'FS' }],
  },
  {
    id: '26',
    name: 'Code Refactoring',
    startDate: formatISO(setTime(addDays(baseDate, 75), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 77), 17)),
    parentId: null,
    sequence: '21',
    dependencies: [{ targetId: '25', type: 'FS' }],
  },
  {
    id: '27',
    name: 'Mobile Optimization',
    startDate: formatISO(setTime(addDays(baseDate, 78), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 80), 17)),
    parentId: null,
    sequence: '22',
    dependencies: [{ targetId: '26', type: 'FS' }],
  },
  {
    id: '28',
    name: 'Testing Environment Setup',
    startDate: formatISO(setTime(addDays(baseDate, 81), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 83), 17)),
    parentId: null,
    sequence: '23',
    dependencies: [{ targetId: '27', type: 'FS' }],
  },
  {
    id: '29',
    name: 'Load Testing',
    startDate: formatISO(setTime(addDays(baseDate, 84), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 86), 17)),
    parentId: null,
    sequence: '24',
    dependencies: [{ targetId: '28', type: 'FS' }],
  },
  {
    id: '30',
    name: 'API Rate Limiting Implementation',
    startDate: formatISO(setTime(addDays(baseDate, 87), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 89), 17)),
    parentId: null,
    sequence: '25',
    dependencies: [{ targetId: '29', type: 'FS' }],
  },
  {
    id: '31',
    name: 'Security Audit',
    startDate: formatISO(setTime(addDays(baseDate, 90), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 92), 17)),
    parentId: null,
    sequence: '26',
    dependencies: [{ targetId: '30', type: 'FS' }],
  },
  {
    id: '32',
    name: 'Documentation Update',
    startDate: formatISO(setTime(addDays(baseDate, 93), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 96), 17)),
    parentId: null,
    sequence: '27',
    dependencies: [{ targetId: '31', type: 'FS' }],
  },
  {
    id: '33',
    name: 'Feature Freeze',
    startDate: formatISO(setTime(addDays(baseDate, 97), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 99), 17)),
    parentId: null,
    sequence: '28',
    dependencies: [{ targetId: '32', type: 'FS' }],
  },
  {
    id: '34',
    name: 'Release Candidate Preparation',
    startDate: formatISO(setTime(addDays(baseDate, 100), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 102), 17)),
    parentId: null,
    sequence: '29',
    dependencies: [{ targetId: '33', type: 'FS' }],
  },
  {
    id: '35',
    name: 'User Documentation',
    startDate: formatISO(setTime(addDays(baseDate, 103), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 105), 17)),
    parentId: null,
    sequence: '30',
    dependencies: [{ targetId: '32', type: 'SS' }],
  },
  {
    id: '36',
    name: 'Final Testing',
    startDate: formatISO(setTime(addDays(baseDate, 106), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 109), 17)),
    parentId: null,
    sequence: '31',
    dependencies: [{ targetId: '34', type: 'FS' }],
  },
  {
    id: '37',
    name: 'Code Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 110), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 112), 17)),
    parentId: null,
    sequence: '32',
    dependencies: [{ targetId: '36', type: 'FS' }],
  },
  {
    id: '38',
    name: 'Monitoring Setup',
    startDate: formatISO(setTime(addDays(baseDate, 113), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 115), 17)),
    parentId: null,
    sequence: '33',
    dependencies: [{ targetId: '37', type: 'FS' }],
  },
  {
    id: '39',
    name: 'Post-Deployment Testing',
    startDate: formatISO(setTime(addDays(baseDate, 116), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 118), 17)),
    parentId: null,
    sequence: '34',
    dependencies: [{ targetId: '38', type: 'FS' }],
  },
  {
    id: '40',
    name: 'Bug Tracking and Resolution',
    startDate: formatISO(setTime(addDays(baseDate, 119), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 121), 17)),
    parentId: null,
    sequence: '35',
    dependencies: [{ targetId: '39', type: 'FS' }],
  },
  {
    id: '41',
    name: 'Feature Enhancement Planning',
    startDate: formatISO(setTime(addDays(baseDate, 122), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 124), 17)),
    parentId: null,
    sequence: '36',
    dependencies: [{ targetId: '40', type: 'FS' }],
  },
  {
    id: '42',
    name: 'New Feature Design',
    startDate: formatISO(setTime(addDays(baseDate, 125), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 128), 17)),
    parentId: '41',
    sequence: '36.1',
    dependencies: [{ targetId: '41', type: 'FS' }],
  },
  {
    id: '43',
    name: 'New Feature Development',
    startDate: formatISO(setTime(addDays(baseDate, 129), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 133), 17)),
    parentId: '42',
    sequence: '36.2',
    dependencies: [{ targetId: '42', type: 'FS' }],
  },
  {
    id: '44',
    name: 'Testing of New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 134), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 136), 17)),
    parentId: '43',
    sequence: '36.3',
    dependencies: [{ targetId: '43', type: 'FS' }],
  },
  {
    id: '45',
    name: 'User Acceptance Testing (UAT) for New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 137), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 140), 17)),
    parentId: '44',
    sequence: '36.4',
    dependencies: [{ targetId: '44', type: 'FS' }],
  },
  {
    id: '46',
    name: 'Feature Release',
    startDate: formatISO(setTime(addDays(baseDate, 141), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 143), 17)),
    parentId: null,
    sequence: '37',
    dependencies: [{ targetId: '45', type: 'FS' }],
  },
  {
    id: '47',
    name: 'Performance Testing for New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 144), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 146), 17)),
    parentId: null,
    sequence: '38',
    dependencies: [{ targetId: '46', type: 'FS' }],
  },
  {
    id: '48',
    name: 'Final Code Review for New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 147), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 149), 17)),
    parentId: null,
    sequence: '39',
    dependencies: [{ targetId: '47', type: 'FS' }],
  },
  {
    id: '49',
    name: 'Production Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 150), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 152), 17)),
    parentId: null,
    sequence: '40',
    dependencies: [{ targetId: '48', type: 'FS' }],
  },
  {
    id: '50',
    name: 'Post-Deployment Support',
    startDate: formatISO(setTime(addDays(baseDate, 153), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 156), 17)),
    parentId: null,
    sequence: '41',
    dependencies: [{ targetId: '49', type: 'FS' }],
  },
];

export default sourceTasks;
