import { Task } from './src/types/task';

function addDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setUTCDate(result.getUTCDate() + days);
  return result;
}

function setTime(date: Date, hours: number, minutes = 0, seconds = 0): Date {
  const result = new Date(date);
  result.setUTCHours(hours, minutes, seconds, 0);
  return result;
}

function formatISO(date: Date): string {
  return date.toISOString().split('.')[0] + 'Z';
}

const today = new Date();
const baseDate = setTime(new Date(today), 0, 0, 0);

/** The most recent Monday (UTC), so weekends always land on the same day offsets */
const mondayBase = setTime(
  addDays(baseDate, -((baseDate.getUTCDay() + 6) % 7)),
  0,
  0,
  0
);

/** Day `offset` from the anchor Monday, at `hours` o'clock UTC */
const at = (offset: number, hours: number) =>
  formatISO(setTime(addDays(mondayBase, offset), hours));

export const sourceTasks: Task[] = [
  {
    id: '1',
    name: 'Project Kickoff',
    startDate: formatISO(setTime(addDays(baseDate, 0), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 0), 11)),
    parentId: null,
    sequence: '1',
    progress: 100,
    dependencies: [],
  },
  {
    id: '2',
    name: 'Requirement Gathering',
    startDate: formatISO(setTime(addDays(baseDate, 1), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 4), 17)),
    parentId: null,
    sequence: '2',
    progress: 100,
    dependencies: [{ targetId: '1', type: 'FS' }],
  },
  {
    id: '3',
    name: 'Design Kickoff Meeting',
    startDate: formatISO(setTime(addDays(baseDate, 3), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 3), 17)),
    parentId: null,
    sequence: '2.1',
    progress: 80,
    dependencies: [{ targetId: '2', type: 'SS' }],
  },
  {
    id: '4',
    name: 'Technical Design Review',
    startDate: formatISO(setTime(addDays(baseDate, 5), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 7), 17)),
    parentId: null,
    sequence: '3',
    progress: 60,
    dependencies: [{ targetId: '3', type: 'FS' }],
  },
  {
    id: '51',
    name: 'Design Sign-off',
    startDate: formatISO(setTime(addDays(baseDate, 8), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 8), 9)),
    parentId: null,
    sequence: '3.5',
    type: 'milestone',
    dependencies: [{ targetId: '4', type: 'FS' }],
  },
  {
    id: '5',
    name: 'Frontend Architecture Planning',
    startDate: formatISO(setTime(addDays(baseDate, 8), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 10), 17)),
    parentId: null,
    sequence: '4',
    progress: 45,
    dependencies: [{ targetId: '4', type: 'FS' }],
  },
  {
    id: '6',
    name: 'Backend Architecture Planning',
    startDate: formatISO(setTime(addDays(baseDate, 9), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 11), 17)),
    parentId: null,
    sequence: '5',
    progress: 30,
    dependencies: [{ targetId: '4', type: 'FS' }],
  },
  {
    id: '7',
    name: 'Frontend UI Design',
    startDate: formatISO(setTime(addDays(baseDate, 12), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 17), 17)),
    parentId: '5',
    sequence: '4.1',
    progress: 15,
    dependencies: [{ targetId: '5', type: 'FS' }],
  },
  {
    id: '8',
    name: 'Backend Database Schema Design',
    startDate: formatISO(setTime(addDays(baseDate, 14), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 17), 17)),
    parentId: '6',
    sequence: '5.1',
    progress: 5,
    dependencies: [{ targetId: '6', type: 'FS' }],
  },
  {
    id: '9',
    name: 'User Authentication Development',
    startDate: formatISO(setTime(addDays(baseDate, 18), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 22), 17)),
    parentId: '7',
    sequence: '6',
    dependencies: [{ targetId: '7', type: 'FS' }],
  },
  {
    id: '10',
    name: 'Payment Integration Development',
    startDate: formatISO(setTime(addDays(baseDate, 18), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 22), 17)),
    parentId: '8',
    sequence: '7',
    dependencies: [{ targetId: '8', type: 'FS' }],
  },
  {
    id: '11',
    name: 'API Endpoints Development',
    startDate: formatISO(setTime(addDays(baseDate, 23), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 27), 17)),
    parentId: '9',
    sequence: '6.1',
    dependencies: [{ targetId: '9', type: 'SS' }],
  },
  {
    id: '12',
    name: 'Frontend Component Development',
    startDate: formatISO(setTime(addDays(baseDate, 23), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 28), 17)),
    parentId: '7',
    sequence: '4.2',
    dependencies: [{ targetId: '7', type: 'SS' }],
  },
  {
    id: '13',
    name: 'Integration of Frontend and Backend',
    startDate: formatISO(setTime(addDays(baseDate, 28), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 31), 17)),
    parentId: null,
    sequence: '8',
    dependencies: [
      { targetId: '11', type: 'FS' },
      { targetId: '12', type: 'FS' },
    ],
  },
  {
    id: '14',
    name: 'Performance Optimization',
    startDate: formatISO(setTime(addDays(baseDate, 32), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 35), 17)),
    parentId: null,
    sequence: '9',
    dependencies: [{ targetId: '13', type: 'FS' }],
  },
  {
    id: '15',
    name: 'User Acceptance Testing (UAT)',
    startDate: formatISO(setTime(addDays(baseDate, 36), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 39), 17)),
    parentId: null,
    sequence: '10',
    dependencies: [{ targetId: '14', type: 'FS' }],
  },
  {
    id: '16',
    name: 'Bug Fixing and Refinement',
    startDate: formatISO(setTime(addDays(baseDate, 40), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 43), 17)),
    parentId: null,
    sequence: '11',
    dependencies: [{ targetId: '15', type: 'FS' }],
  },
  {
    id: '17',
    name: 'Pre-Release Demo',
    startDate: formatISO(setTime(addDays(baseDate, 44), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 46), 17)),
    parentId: null,
    sequence: '12',
    dependencies: [{ targetId: '16', type: 'FS' }],
  },
  {
    id: '18',
    name: 'Final Release and Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 47), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 50), 17)),
    parentId: null,
    sequence: '13',
    dependencies: [{ targetId: '17', type: 'FS' }],
  },
  {
    id: '19',
    name: 'Post-Release Monitoring',
    startDate: formatISO(setTime(addDays(baseDate, 51), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 53), 17)),
    parentId: null,
    sequence: '14',
    dependencies: [{ targetId: '18', type: 'FS' }],
  },
  {
    id: '20',
    name: 'Community Engagement and Feedback Collection',
    startDate: formatISO(setTime(addDays(baseDate, 54), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 57), 17)),
    parentId: null,
    sequence: '15',
    dependencies: [{ targetId: '19', type: 'FS' }],
  },
  {
    id: '21',
    name: 'Feature Iteration and Updates',
    startDate: formatISO(setTime(addDays(baseDate, 58), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 60), 17)),
    parentId: null,
    sequence: '16',
    dependencies: [{ targetId: '20', type: 'SS' }],
  },
  {
    id: '22',
    name: 'Maintenance and Bug Fixing',
    startDate: formatISO(setTime(addDays(baseDate, 61), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 63), 17)),
    parentId: null,
    sequence: '17',
    dependencies: [{ targetId: '21', type: 'FS' }],
  },
  {
    id: '23',
    name: 'Database Optimization',
    startDate: formatISO(setTime(addDays(baseDate, 64), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 67), 17)),
    parentId: null,
    sequence: '18',
    dependencies: [{ targetId: '22', type: 'FS' }],
  },
  {
    id: '24',
    name: 'Scaling Infrastructure',
    startDate: formatISO(setTime(addDays(baseDate, 68), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 71), 17)),
    parentId: null,
    sequence: '19',
    dependencies: [{ targetId: '23', type: 'FS' }],
  },
  {
    id: '25',
    name: 'Security Patch Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 72), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 74), 17)),
    parentId: null,
    sequence: '20',
    dependencies: [{ targetId: '24', type: 'FS' }],
  },
  {
    id: '26',
    name: 'Code Refactoring',
    startDate: formatISO(setTime(addDays(baseDate, 75), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 77), 17)),
    parentId: null,
    sequence: '21',
    dependencies: [{ targetId: '25', type: 'FS' }],
  },
  {
    id: '27',
    name: 'Mobile Optimization',
    startDate: formatISO(setTime(addDays(baseDate, 78), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 80), 17)),
    parentId: null,
    sequence: '22',
    dependencies: [{ targetId: '26', type: 'FS' }],
  },
  {
    id: '28',
    name: 'Testing Environment Setup',
    startDate: formatISO(setTime(addDays(baseDate, 81), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 83), 17)),
    parentId: null,
    sequence: '23',
    dependencies: [{ targetId: '27', type: 'FS' }],
  },
  {
    id: '29',
    name: 'Load Testing',
    startDate: formatISO(setTime(addDays(baseDate, 84), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 86), 17)),
    parentId: null,
    sequence: '24',
    dependencies: [{ targetId: '28', type: 'FS' }],
  },
  {
    id: '30',
    name: 'API Rate Limiting Implementation',
    startDate: formatISO(setTime(addDays(baseDate, 87), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 89), 17)),
    parentId: null,
    sequence: '25',
    dependencies: [{ targetId: '29', type: 'FS' }],
  },
  {
    id: '31',
    name: 'Security Audit',
    startDate: formatISO(setTime(addDays(baseDate, 90), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 92), 17)),
    parentId: null,
    sequence: '26',
    dependencies: [{ targetId: '30', type: 'FS' }],
  },
  {
    id: '32',
    name: 'Documentation Update',
    startDate: formatISO(setTime(addDays(baseDate, 93), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 96), 17)),
    parentId: null,
    sequence: '27',
    dependencies: [{ targetId: '31', type: 'FS' }],
  },
  {
    id: '33',
    name: 'Feature Freeze',
    startDate: formatISO(setTime(addDays(baseDate, 97), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 99), 17)),
    parentId: null,
    sequence: '28',
    dependencies: [{ targetId: '32', type: 'FS' }],
  },
  {
    id: '34',
    name: 'Release Candidate Preparation',
    startDate: formatISO(setTime(addDays(baseDate, 100), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 102), 17)),
    parentId: null,
    sequence: '29',
    dependencies: [{ targetId: '33', type: 'FS' }],
  },
  {
    id: '35',
    name: 'User Documentation',
    startDate: formatISO(setTime(addDays(baseDate, 103), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 105), 17)),
    parentId: null,
    sequence: '30',
    dependencies: [{ targetId: '32', type: 'SS' }],
  },
  {
    id: '36',
    name: 'Final Testing',
    startDate: formatISO(setTime(addDays(baseDate, 106), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 109), 17)),
    parentId: null,
    sequence: '31',
    dependencies: [{ targetId: '34', type: 'FS' }],
  },
  {
    id: '37',
    name: 'Code Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 110), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 112), 17)),
    parentId: null,
    sequence: '32',
    dependencies: [{ targetId: '36', type: 'FS' }],
  },
  {
    id: '38',
    name: 'Monitoring Setup',
    startDate: formatISO(setTime(addDays(baseDate, 113), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 115), 17)),
    parentId: null,
    sequence: '33',
    dependencies: [{ targetId: '37', type: 'FS' }],
  },
  {
    id: '39',
    name: 'Post-Deployment Testing',
    startDate: formatISO(setTime(addDays(baseDate, 116), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 118), 17)),
    parentId: null,
    sequence: '34',
    dependencies: [{ targetId: '38', type: 'FS' }],
  },
  {
    id: '40',
    name: 'Bug Tracking and Resolution',
    startDate: formatISO(setTime(addDays(baseDate, 119), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 121), 17)),
    parentId: null,
    sequence: '35',
    dependencies: [{ targetId: '39', type: 'FS' }],
  },
  {
    id: '41',
    name: 'Feature Enhancement Planning',
    startDate: formatISO(setTime(addDays(baseDate, 122), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 124), 17)),
    parentId: null,
    sequence: '36',
    dependencies: [{ targetId: '40', type: 'FS' }],
  },
  {
    id: '42',
    name: 'New Feature Design',
    startDate: formatISO(setTime(addDays(baseDate, 125), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 128), 17)),
    parentId: '41',
    sequence: '36.1',
    dependencies: [{ targetId: '41', type: 'FS' }],
  },
  {
    id: '43',
    name: 'New Feature Development',
    startDate: formatISO(setTime(addDays(baseDate, 129), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 133), 17)),
    parentId: '42',
    sequence: '36.2',
    dependencies: [{ targetId: '42', type: 'FS' }],
  },
  {
    id: '44',
    name: 'Testing of New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 134), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 136), 17)),
    parentId: '43',
    sequence: '36.3',
    dependencies: [{ targetId: '43', type: 'FS' }],
  },
  {
    id: '45',
    name: 'User Acceptance Testing (UAT) for New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 137), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 140), 17)),
    parentId: '44',
    sequence: '36.4',
    dependencies: [{ targetId: '44', type: 'FS' }],
  },
  {
    id: '46',
    name: 'Feature Release',
    startDate: formatISO(setTime(addDays(baseDate, 141), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 143), 17)),
    parentId: null,
    sequence: '37',
    dependencies: [{ targetId: '45', type: 'FS' }],
  },
  {
    id: '47',
    name: 'Performance Testing for New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 144), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 146), 17)),
    parentId: null,
    sequence: '38',
    dependencies: [{ targetId: '46', type: 'FS' }],
  },
  {
    id: '48',
    name: 'Final Code Review for New Feature',
    startDate: formatISO(setTime(addDays(baseDate, 147), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 149), 17)),
    parentId: null,
    sequence: '39',
    dependencies: [{ targetId: '47', type: 'FS' }],
  },
  {
    id: '49',
    name: 'Production Deployment',
    startDate: formatISO(setTime(addDays(baseDate, 150), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 152), 17)),
    parentId: null,
    sequence: '40',
    dependencies: [{ targetId: '48', type: 'FS' }],
  },
  {
    id: '50',
    name: 'Post-Deployment Support',
    startDate: formatISO(setTime(addDays(baseDate, 153), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 156), 17)),
    parentId: null,
    sequence: '41',
    dependencies: [{ targetId: '49', type: 'FS' }],
  },

  // ===== Nested project (hierarchy demo) =====
  // Four levels deep with several siblings. Parent dates and progress are recomputed from
  // the children, so the values written here only show up with hierarchy off.
  {
    id: '60',
    name: 'Mobile App Launch',
    startDate: formatISO(setTime(addDays(baseDate, 157), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 181), 17)),
    parentId: null,
    sequence: '42',
  },
  {
    id: '61',
    name: 'Discovery',
    startDate: formatISO(setTime(addDays(baseDate, 157), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 162), 17)),
    parentId: '60',
    sequence: '42.1',
  },
  {
    id: '62',
    name: 'User Interviews',
    startDate: formatISO(setTime(addDays(baseDate, 157), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 160), 17)),
    parentId: '61',
    sequence: '42.1.1',
    progress: 100,
  },
  {
    id: '63',
    name: 'Competitive Analysis',
    startDate: formatISO(setTime(addDays(baseDate, 158), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 162), 17)),
    parentId: '61',
    sequence: '42.1.2',
    progress: 60,
  },
  {
    id: '64',
    name: 'Build',
    startDate: formatISO(setTime(addDays(baseDate, 163), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 175), 17)),
    parentId: '60',
    sequence: '42.2',
  },
  {
    id: '65',
    name: 'iOS Client',
    startDate: formatISO(setTime(addDays(baseDate, 163), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 172), 17)),
    parentId: '64',
    sequence: '42.2.1',
  },
  {
    id: '66',
    name: 'iOS Auth Flow',
    startDate: formatISO(setTime(addDays(baseDate, 163), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 168), 17)),
    parentId: '65',
    sequence: '42.2.1.1',
    progress: 80,
    dependencies: [{ targetId: '63', type: 'FS' }],
  },
  {
    id: '67',
    name: 'iOS Offline Cache',
    startDate: formatISO(setTime(addDays(baseDate, 166), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 172), 17)),
    parentId: '65',
    sequence: '42.2.1.2',
    progress: 30,
  },
  {
    id: '68',
    name: 'Android Client',
    startDate: formatISO(setTime(addDays(baseDate, 165), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 175), 17)),
    parentId: '64',
    sequence: '42.2.2',
  },
  {
    id: '69',
    name: 'Android Auth Flow',
    startDate: formatISO(setTime(addDays(baseDate, 165), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 170), 17)),
    parentId: '68',
    sequence: '42.2.2.1',
    progress: 20,
  },
  {
    id: '70',
    name: 'Push Notifications',
    startDate: formatISO(setTime(addDays(baseDate, 171), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 175), 17)),
    parentId: '68',
    sequence: '42.2.2.2',
    progress: 0,
    dependencies: [{ targetId: '69', type: 'FS' }],
  },
  {
    id: '71',
    name: 'Launch',
    startDate: formatISO(setTime(addDays(baseDate, 176), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 181), 17)),
    parentId: '60',
    sequence: '42.3',
  },
  {
    id: '72',
    name: 'Store Submission',
    startDate: formatISO(setTime(addDays(baseDate, 176), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 179), 17)),
    parentId: '71',
    sequence: '42.3.1',
    progress: 0,
    dependencies: [{ targetId: '70', type: 'FS' }],
  },
  {
    id: '73',
    name: 'Public Launch',
    startDate: formatISO(setTime(addDays(baseDate, 181), 9)),
    endDate: formatISO(setTime(addDays(baseDate, 181), 9)),
    parentId: '71',
    sequence: '42.3.2',
    type: 'milestone',
    dependencies: [{ targetId: '72', type: 'FS' }],
  },
];

/**
 * ===== Scheduling demo =====
 *
 * A small project built to exercise the scheduling engine, anchored to the most recent
 * Monday so the weekends always fall on the same day offsets.
 *
 * Tasks run 09:00-17:00 and milestones sit at 17:00, so a link with no lag means "the day
 * after". The chain s1 -> s2 -> s5 -> s7 -> s8 -> s10 -> s11 is laid out tight, which makes
 * it the critical path; the design branch (s3, s4, s6) and the parallel perf work (s9) are
 * deliberately loose and carry slack. Two tasks and the launch milestone carry baselines,
 * and post-launch support is pinned with `manuallyScheduled`.
 *
 * Expected with `criticalPath` on (calendar days):
 *   critical: s1 s2 s5 s7 s8 s10 s11 - total slack 0
 *   slack:    s3 4, s4 4, s6 1, s9 3
 */
export const schedulingTasks: Task[] = [
  {
    id: 's1',
    name: 'Project kickoff',
    startDate: at(0, 9),
    endDate: at(0, 17),
    parentId: null,
    sequence: '1',
    progress: 60,
    dependencies: [],
  },
  {
    id: 's2',
    name: 'Content audit',
    startDate: at(1, 9),
    endDate: at(4, 17),
    parentId: null,
    sequence: '2',
    progress: 70,
    // Planned to wrap a day earlier - the baseline bar shows the slip
    baselineStart: at(1, 9),
    baselineEnd: at(3, 17),
    dependencies: [{ targetId: 's1', type: 'FS' }],
  },
  {
    id: 's3',
    name: 'Visual design',
    startDate: at(1, 9),
    endDate: at(3, 17),
    parentId: null,
    sequence: '3',
    progress: 100,
    dependencies: [{ targetId: 's1', type: 'FS' }],
  },
  {
    id: 's4',
    name: 'Design sign-off',
    startDate: at(3, 17),
    endDate: at(3, 17),
    parentId: null,
    sequence: '4',
    type: 'milestone',
    dependencies: [{ targetId: 's3', type: 'FS' }],
  },
  {
    id: 's5',
    name: 'CMS migration',
    startDate: at(5, 9),
    endDate: at(11, 17),
    parentId: null,
    sequence: '5',
    progress: 30,
    baselineStart: at(5, 9),
    baselineEnd: at(9, 17),
    dependencies: [{ targetId: 's2', type: 'FS' }],
  },
  {
    id: 's6',
    name: 'Template build',
    startDate: at(8, 9),
    endDate: at(10, 17),
    parentId: null,
    sequence: '6',
    progress: 20,
    // A day of lag after sign-off, and started later than it had to - hence its slack
    dependencies: [{ targetId: 's4', type: 'FS', lag: 1 }],
  },
  {
    id: 's7',
    name: 'Content load',
    startDate: at(12, 9),
    endDate: at(15, 17),
    parentId: null,
    sequence: '7',
    progress: 0,
    dependencies: [
      { targetId: 's5', type: 'FS' },
      { targetId: 's6', type: 'FS' },
    ],
  },
  {
    id: 's8',
    name: 'QA pass',
    startDate: at(16, 9),
    endDate: at(20, 17),
    parentId: null,
    sequence: '8',
    progress: 0,
    dependencies: [{ targetId: 's7', type: 'FS' }],
  },
  {
    id: 's9',
    name: 'Performance tuning',
    startDate: at(16, 9),
    endDate: at(17, 17),
    parentId: null,
    sequence: '9',
    progress: 0,
    // Starts alongside the content load rather than after it
    dependencies: [{ targetId: 's7', type: 'SS' }],
  },
  {
    id: 's10',
    name: 'Launch',
    startDate: at(20, 17),
    endDate: at(20, 17),
    parentId: null,
    sequence: '10',
    type: 'milestone',
    baselineStart: at(19, 17),
    dependencies: [
      { targetId: 's8', type: 'FS' },
      { targetId: 's9', type: 'FS' },
    ],
  },
  {
    id: 's11',
    name: 'Post-launch support',
    startDate: at(21, 9),
    endDate: at(24, 17),
    parentId: null,
    sequence: '11',
    progress: 0,
    // The engine never moves this one, whatever happens upstream
    manuallyScheduled: true,
    dependencies: [{ targetId: 's10', type: 'FS' }],
  },
];

export default sourceTasks;
